export function UiPropertyEditor({ element, onUpdate, onToggleFree }) {
  const props = element.props || {};
  if (element.type === 'Screen') return <div className="ui-property-grid">
    <label><input type="checkbox" checked={Boolean(props.free)} onChange={() => onToggleFree(element)} /> Free layout (drag anywhere)</label>
    <label>Max width<input type="number" value={props.maxWidth ?? 800} onChange={event => onUpdate({ maxWidth: Number(event.target.value) })} /></label>
    <label>Padding<input type="number" value={props.padding ?? 32} onChange={event => onUpdate({ padding: Number(event.target.value) })} /></label>
    <label>Background<input type="color" value={props.background || '#ffffff'} onChange={event => onUpdate({ background: event.target.value })} /></label>
    <label>Text color<input type="color" value={props.color || '#17211b'} onChange={event => onUpdate({ color: event.target.value })} /></label>
  </div>;
  if (element.type === 'Layout') return <div className="ui-property-grid"><label><input type="checkbox" checked={Boolean(props.free)} onChange={() => onToggleFree(element)} /> Free layout</label><label>Direction<select value={props.direction || 'column'} onChange={event => onUpdate({ direction: event.target.value })}><option>column</option><option>row</option></select></label><label>Gap<input type="number" value={props.gap ?? 16} onChange={event => onUpdate({ gap: Number(event.target.value) })} /></label></div>;
  if (element.type === 'Text') return <div className="ui-property-grid"><label>Text<textarea value={props.text || ''} onChange={event => onUpdate({ text: event.target.value })} /></label><label>Variant<select value={props.variant || 'body'} onChange={event => onUpdate({ variant: event.target.value })}><option>body</option><option>heading</option></select></label><label>Font size<input value={props.fontSize || ''} placeholder="e.g. 20px" onChange={event => onUpdate({ fontSize: event.target.value })} /></label></div>;
  if (element.type === 'Media') return <div className="ui-property-grid"><label>Media type<select value={props.mediaType || 'image'} onChange={event => onUpdate({ mediaType: event.target.value })}><option>image</option><option>audio</option><option>video</option></select></label><label>Source URL<input value={props.sourceUrl || ''} onChange={event => onUpdate({ sourceUrl: event.target.value })} /></label><label>Alt text<input value={props.alt || ''} onChange={event => onUpdate({ alt: event.target.value })} /></label><label>Fit<select value={props.fit || 'contain'} onChange={event => onUpdate({ fit: event.target.value })}><option>contain</option><option>cover</option><option>fill</option></select></label><label><input type="checkbox" checked={props.controls !== false} onChange={event => onUpdate({ controls: event.target.checked })} /> Show controls</label><label><input type="checkbox" checked={Boolean(props.autoPlay)} onChange={event => onUpdate({ autoPlay: event.target.checked })} /> Auto-play</label></div>;
  if (element.type === 'Input') return <div className="ui-property-grid"><label>Response name<input value={props.name || ''} onChange={event => onUpdate({ name: event.target.value })} /></label><label>Label<input value={props.label || ''} onChange={event => onUpdate({ label: event.target.value })} /></label><label>Input type<select value={props.inputType || 'text'} onChange={event => onUpdate({ inputType: event.target.value })}><option>text</option><option>textarea</option><option>number</option><option>rating</option><option>checkbox</option></select></label>{props.inputType !== 'checkbox' && <label>Placeholder<input value={props.placeholder || ''} onChange={event => onUpdate({ placeholder: event.target.value })} /></label>}<label><input type="checkbox" checked={Boolean(props.required)} onChange={event => onUpdate({ required: event.target.checked })} /> Required</label>{props.inputType === 'rating' && <><label>Min<input type="number" value={props.min ?? 1} onChange={event => onUpdate({ min: Number(event.target.value) })} /></label><label>Max<input type="number" value={props.max ?? 7} onChange={event => onUpdate({ max: Number(event.target.value) })} /></label></>}</div>;
  if (element.type === 'Button') return <div className="ui-property-grid"><label>Label<input value={props.label || ''} onChange={event => onUpdate({ label: event.target.value })} /></label><label>Variant<select value={props.variant || 'primary'} onChange={event => onUpdate({ variant: event.target.value })}><option>primary</option><option>secondary</option></select></label></div>;
  if (element.type === 'Progress') return <div className="ui-property-grid"><label>Label<input value={props.label || ''} onChange={event => onUpdate({ label: event.target.value })} /></label><label>Value<input type="number" value={props.value ?? 0} onChange={event => onUpdate({ value: Number(event.target.value) })} /></label><label>Maximum<input type="number" value={props.max ?? 100} onChange={event => onUpdate({ max: Number(event.target.value) })} /></label></div>;
  if (element.type === 'Html') return <div className="ui-property-grid"><label>HTML fragment<textarea value={props.html || ''} rows={5} onChange={event => onUpdate({ html: event.target.value })} /></label></div>;
  if (element.type === 'Divider') return <div className="ui-property-grid"><label>Orientation<select value={props.orientation || 'horizontal'} onChange={event => onUpdate({ orientation: event.target.value })}><option>horizontal</option><option>vertical</option></select></label><label>Thickness<input type="number" min="0.5" step="0.5" value={props.thickness ?? 1} onChange={event => onUpdate({ thickness: Number(event.target.value) })} /></label></div>;
  return null;
}
